"""
Salary Prediction Service for CareerOS AI Backend.
Provides modular, explainable market benchmark salary estimations based on target roles,
experience level, technical competencies, education, and domain certifications.

IMPORTANT DISCLAIMER:
All compensation figures generated by this service represent general estimated market
benchmark ranges and guidance. They are not guaranteed offers or verified real-time wage data.
"""

import math
import logging

logger = logging.getLogger(__name__)

class SalaryService:
    """
    Modular salary estimation service designed for easy future integration with
    real-time market providers (e.g., Bureau of Labor Statistics, Glassdoor APIs).
    """

    # Baseline US/International Tech Industry Estimated Benchmarks (Annual USD)
    # Formatted as: {role_key: {experience_level: (min, max, median)}}
    MARKET_BENCHMARKS = {
        "python developer": {
            "Entry Level": (50000, 80000, 65000),
            "Junior": (60000, 90000, 75000),
            "Mid-Level": (85000, 125000, 105000),
            "Senior": (120000, 170000, 145000),
            "Lead / Principal": (150000, 210000, 180000)
        },
        "backend developer": {
            "Entry Level": (50000, 80000, 65000),
            "Junior": (60000, 90000, 75000),
            "Mid-Level": (85000, 130000, 107500),
            "Senior": (125000, 175000, 150000),
            "Lead / Principal": (155000, 220000, 187500)
        },
        "full stack developer": {
            "Entry Level": (52000, 82000, 67000),
            "Junior": (62000, 92000, 77000),
            "Mid-Level": (90000, 135000, 112500),
            "Senior": (130000, 180000, 155000),
            "Lead / Principal": (160000, 225000, 192500)
        },
        "frontend developer": {
            "Entry Level": (45000, 75000, 60000),
            "Junior": (55000, 85000, 70000),
            "Mid-Level": (80000, 120000, 100000),
            "Senior": (115000, 160000, 137500),
            "Lead / Principal": (140000, 195000, 167500)
        },
        "react developer": {
            "Entry Level": (48000, 78000, 63000),
            "Junior": (58000, 88000, 73000),
            "Mid-Level": (85000, 125000, 105000),
            "Senior": (120000, 165000, 142500),
            "Lead / Principal": (145000, 200000, 172500)
        },
        "data analyst": {
            "Entry Level": (45000, 70000, 57500),
            "Junior": (55000, 80000, 67500),
            "Mid-Level": (75000, 110000, 92500),
            "Senior": (100000, 140000, 120000),
            "Lead / Principal": (125000, 170000, 147500)
        },
        "data scientist": {
            "Entry Level": (65000, 95000, 80000),
            "Junior": (75000, 105000, 90000),
            "Mid-Level": (100000, 150000, 125000),
            "Senior": (140000, 195000, 167500),
            "Lead / Principal": (175000, 240000, 207500)
        },
        "machine learning engineer": {
            "Entry Level": (70000, 105000, 87500),
            "Junior": (80000, 115000, 97500),
            "Mid-Level": (110000, 165000, 137500),
            "Senior": (150000, 215000, 182500),
            "Lead / Principal": (185000, 260000, 222500)
        },
        "ai engineer": {
            "Entry Level": (75000, 110000, 92500),
            "Junior": (85000, 125000, 105000),
            "Mid-Level": (120000, 180000, 150000),
            "Senior": (160000, 235000, 197500),
            "Lead / Principal": (200000, 300000, 250000)
        },
        "java developer": {
            "Entry Level": (50000, 80000, 65000),
            "Junior": (60000, 90000, 75000),
            "Mid-Level": (85000, 130000, 107500),
            "Senior": (120000, 170000, 145000),
            "Lead / Principal": (150000, 210000, 180000)
        },
        "cloud engineer": {
            "Entry Level": (60000, 90000, 75000),
            "Junior": (70000, 105000, 87500),
            "Mid-Level": (95000, 145000, 120000),
            "Senior": (135000, 190000, 162500),
            "Lead / Principal": (165000, 235000, 200000)
        },
        "devops engineer": {
            "Entry Level": (60000, 90000, 75000),
            "Junior": (70000, 105000, 87500),
            "Mid-Level": (95000, 145000, 120000),
            "Senior": (135000, 190000, 162500),
            "Lead / Principal": (165000, 235000, 200000)
        },
        "software engineer": {
            "Entry Level": (50000, 80000, 65000),
            "Junior": (60000, 90000, 75000),
            "Mid-Level": (85000, 130000, 107500),
            "Senior": (120000, 175000, 147500),
            "Lead / Principal": (155000, 220000, 187500)
        }
    }

    @classmethod
    def determine_experience_level(cls, resume_data: dict) -> str:
        """
        Analyze parsed resume experience entries and summary text to classify
        candidate experience level deterministically without exaggerating seniority.
        """
        exp_list = resume_data.get("experience") or []
        parsed = resume_data.get("parsed_data") or {}
        if not exp_list and isinstance(parsed, dict):
            exp_list = parsed.get("experience") or []
            
        summary = ""
        if isinstance(parsed, dict):
            summary = str(parsed.get("summary") or "").lower()
        raw_text = str(resume_data.get("extracted_text", "")).lower()
        
        num_roles = len(exp_list) if isinstance(exp_list, list) else 0
        
        # Check explicit indicators in text or role counts
        if any(term in summary or term in raw_text[:300] for term in ["lead engineer", "principal", "10+ years", "12+ years", "8+ years", "director", "architect"]):
            return "Lead / Principal"
        elif any(term in summary or term in raw_text[:300] for term in ["senior engineer", "senior developer", "sr. software", "5+ years", "6+ years", "7+ years"]) or num_roles >= 4:
            return "Senior"
        elif any(term in summary or term in raw_text[:300] for term in ["3+ years", "4+ years", "mid-level", "intermediate"]) or (num_roles >= 2 and num_roles <= 3):
            return "Mid-Level"
        elif any(term in summary or term in raw_text[:300] for term in ["junior developer", "jr.", "1+ year", "2+ years"]) or num_roles == 1:
            return "Junior"
        else:
            return "Entry Level"

    @classmethod
    def predict_salary_range(cls, target_role: str, resume_data: dict, location: str = None, match_percentage: int = 50) -> dict:
        """
        Generate an explainable estimated market salary range based on career target,
        candidate experience, education, certifications, and technical alignment.
        """
        role_clean = (target_role or "Software Engineer").strip().lower()
        exp_level = cls.determine_experience_level(resume_data)
        
        # Match target role benchmark or default to software engineer
        bench_role = role_clean if role_clean in cls.MARKET_BENCHMARKS else "software engineer"
        base_min, base_max, base_median = cls.MARKET_BENCHMARKS[bench_role].get(exp_level, (50000, 80000, 65000))
        
        # Evaluate adjustment factors (Education & Certifications & High Match)
        parsed = resume_data.get("parsed_data") or {}
        edu_str = str(parsed.get("education") or "").lower() if isinstance(parsed, dict) else ""
        cert_str = str(parsed.get("certifications") or "").lower() if isinstance(parsed, dict) else ""
        
        multiplier = 1.0
        reasons = [f"Estimated range based on evaluated {exp_level.lower()} profile and industry benchmarks for {target_role.title()}."]
        
        # Advanced degree adjustment (+5%)
        if any(deg in edu_str for deg in ["master", "m.s.", "ms", "phd", "ph.d", "doctorate"]):
            multiplier += 0.05
            reasons.append("Includes slight benchmark uplift for advanced academic degree.")
            
        # Recognized certification adjustment (+5%)
        if cert_str and len(cert_str.strip()) > 5 and not any(neg in cert_str for neg in ["none", "null"]):
            multiplier += 0.05
            reasons.append("Includes benchmark uplift for professional domain certifications.")
            
        # Strong technical skill alignment
        if match_percentage >= 80:
            multiplier += 0.05
            reasons.append("Strong technical skill match alignment places estimate in upper percentile.")
        elif match_percentage < 40:
            multiplier -= 0.05
            reasons.append("Noticeable skill gaps place estimate conservatively near baseline percentile.")
            
        # Apply multiplier and round to nearest $1000 for clean estimation representation
        est_min = int(round((base_min * multiplier) / 1000.0) * 1000)
        est_max = int(round((base_max * multiplier) / 1000.0) * 1000)
        est_median = int(round((base_median * multiplier) / 1000.0) * 1000)
        
        explanation = " ".join(reasons) + " Note: All values represent general market guidance estimates and are not guaranteed salaries or job offers."
        
        return {
            "career": target_role.strip().title() if target_role else "Software Engineer",
            "experience_level": exp_level,
            "salary_range": {
                "min": est_min,
                "max": est_max,
                "median": est_median,
                "currency": "USD"
            },
            "is_estimate": True,
            "explanation": explanation
        }
