import html2canvas from 'html2canvas';
import { jsPDF } from 'jspdf';

/**
 * CareerOS AI - Professional PDF Report Generator
 * Enterprise-grade PDF exporter using direct html2canvas + jsPDF pipeline.
 * Guarantees zero blank pages, high DPI rendering, and multi-page A4 support.
 */

// Helper to validate analysis data availability
const validateData = (data) => {
  console.log('[PDF Export Debug] Validating analysis data:', data);
  if (!data || typeof data !== 'object' || Object.keys(data).length === 0) {
    alert("Analysis data is not available. Please analyze a resume before downloading.");
    return false;
  }
  return true;
};

// Common Brand Header for PDF Reports
const getReportHeader = (title, candidateInfo = {}, targetRole = 'Software Engineer') => {
  const candidateName = candidateInfo.name || 'Candidate';
  const now = new Date().toLocaleString();

  return `
    <div style="border-bottom: 2px solid #4f46e5; padding-bottom: 12px; margin-bottom: 20px; font-family: system-ui, -apple-system, sans-serif;">
      <div style="display: flex; justify-content: space-between; align-items: flex-start;">
        <div>
          <h1 style="font-size: 24px; font-weight: 800; color: #1e1b4b; margin: 0;">CareerOS AI</h1>
          <p style="font-size: 11px; font-weight: 700; color: #4f46e5; margin: 3px 0 0 0; text-transform: uppercase; letter-spacing: 1px;">
            Professional Career Intelligence & Skill Gap Report
          </p>
        </div>
        <div style="text-align: right;">
          <p style="font-size: 10px; color: #64748b; margin: 0;">Date Generated</p>
          <p style="font-size: 11px; font-weight: 700; color: #0f172a; margin: 2px 0 0 0;">${now}</p>
        </div>
      </div>
      
      <div style="margin-top: 14px; background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 10px 14px; display: flex; justify-content: space-between;">
        <div>
          <span style="font-size: 10px; color: #64748b; text-transform: uppercase; font-weight: 700;">Candidate</span>
          <p style="font-size: 13px; font-weight: 700; color: #0f172a; margin: 2px 0 0 0;">${candidateName}</p>
        </div>
        <div>
          <span style="font-size: 10px; color: #64748b; text-transform: uppercase; font-weight: 700;">Target Role</span>
          <p style="font-size: 13px; font-weight: 700; color: #4f46e5; margin: 2px 0 0 0;">${targetRole}</p>
        </div>
        <div>
          <span style="font-size: 10px; color: #64748b; text-transform: uppercase; font-weight: 700;">Report Type</span>
          <p style="font-size: 13px; font-weight: 700; color: #0f172a; margin: 2px 0 0 0;">${title}</p>
        </div>
      </div>
    </div>
  `;
};

const getReportFooter = () => `
  <div style="margin-top: 30px; border-top: 1px solid #e2e8f0; padding-top: 10px; text-align: center; font-size: 10px; color: #94a3b8; font-family: system-ui, -apple-system, sans-serif;">
    Generated by CareerOS AI • Confidential Career Guidance Report
  </div>
`;

/**
 * Direct Canvas & jsPDF Exporter Engine
 * Converts HTML content or DOM node directly into high-DPI multi-page A4 PDF
 */
const renderPDF = async (htmlContent, filename) => {
  console.log('[PDF Export Debug] Starting direct html2canvas + jsPDF engine for:', filename);
  
  const originalScrollY = window.scrollY;
  window.scrollTo(0, 0); // Reset scroll position to top to eliminate html2canvas offset issues

  // Create staging element at top of document
  const container = document.createElement('div');
  container.style.position = 'absolute';
  container.style.top = '0';
  container.style.left = '0';
  container.style.zIndex = '99999';
  container.style.width = '800px';
  container.style.padding = '32px';
  container.style.backgroundColor = '#ffffff';
  container.style.color = '#0f172a';
  container.style.fontFamily = "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif";
  container.style.boxSizing = 'border-box';
  container.innerHTML = htmlContent;

  document.body.appendChild(container);
  console.log('[PDF Export Debug] Staging container height:', container.offsetHeight, 'width:', container.offsetWidth);

  // Allow browser layout engine to complete reflow & font rendering
  await new Promise(resolve => setTimeout(resolve, 350));

  try {
    const canvas = await html2canvas(container, {
      scale: 2, // High resolution (300 DPI equivalent)
      useCORS: true,
      logging: false,
      backgroundColor: '#ffffff',
      windowWidth: 850,
      scrollX: 0,
      scrollY: 0
    });

    console.log('[PDF Export Debug] Rendered canvas dimensions:', canvas.width, 'x', canvas.height);

    if (canvas.width === 0 || canvas.height === 0) {
      throw new Error('html2canvas produced a 0x0 canvas.');
    }

    const imgData = canvas.toDataURL('image/jpeg', 0.98);
    console.log('[PDF Export Debug] Generated image data length:', imgData.length);

    if (imgData.length < 1000) {
      throw new Error('Generated canvas image data is empty or invalid.');
    }

    // Initialize jsPDF A4 Document
    const pdf = new jsPDF('p', 'mm', 'a4');
    const pageWidth = 210; // mm
    const pageHeight = 297; // mm
    const margin = 10; // mm
    const printableWidth = pageWidth - (margin * 2); // 190mm
    const printableHeight = pageHeight - (margin * 2); // 277mm

    // Calculate height of image when scaled to printable width
    const imgWidth = printableWidth;
    const imgHeight = (canvas.height * printableWidth) / canvas.width;

    let heightLeft = imgHeight;
    let position = margin;

    // Draw first page
    pdf.addImage(imgData, 'JPEG', margin, position, imgWidth, imgHeight);
    heightLeft -= printableHeight;

    // Loop for multi-page document splitting
    while (heightLeft > 0) {
      position = margin - (imgHeight - heightLeft);
      pdf.addPage();
      pdf.addImage(imgData, 'JPEG', margin, position, imgWidth, imgHeight);
      heightLeft -= printableHeight;
    }

    pdf.save(filename);
    console.log('[PDF Export Debug] PDF successfully generated and downloaded:', filename);
    return true;
  } catch (err) {
    console.error('[PDF Export Debug] Exception during direct PDF generation:', err);
    alert("An error occurred while generating the PDF report. Please try again.");
    return false;
  } finally {
    if (document.body.contains(container)) {
      document.body.removeChild(container);
    }
    window.scrollTo(0, originalScrollY); // Restore user's scroll position
  }
};

/**
 * Capture live DOM element directly using html2canvas + jsPDF
 */
export const exportLiveComponentToPDF = async (element, filename) => {
  console.log('[PDF Export Debug] Live DOM export requested for:', filename);

  if (!element || !(element instanceof HTMLElement)) {
    console.error('[PDF Export Debug] Invalid DOM element passed to exportLiveComponentToPDF');
    alert("Analysis component is not ready for export.");
    return false;
  }

  const originalScrollY = window.scrollY;
  window.scrollTo(0, 0);

  await new Promise(resolve => setTimeout(resolve, 400));

  try {
    const canvas = await html2canvas(element, {
      scale: 2,
      useCORS: true,
      logging: false,
      backgroundColor: '#020617', // Match dark slate background
      scrollX: 0,
      scrollY: 0
    });

    console.log('[PDF Export Debug] Live component canvas dimensions:', canvas.width, 'x', canvas.height);

    if (canvas.width === 0 || canvas.height === 0) {
      throw new Error('Live element canvas is 0x0.');
    }

    const imgData = canvas.toDataURL('image/jpeg', 0.98);

    if (imgData.length < 1000) {
      throw new Error('Live canvas image data is empty.');
    }

    const pdf = new jsPDF('p', 'mm', 'a4');
    const pageWidth = 210;
    const pageHeight = 297;
    const margin = 8;
    const printableWidth = pageWidth - (margin * 2);
    const printableHeight = pageHeight - (margin * 2);

    const imgWidth = printableWidth;
    const imgHeight = (canvas.height * printableWidth) / canvas.width;

    let heightLeft = imgHeight;
    let position = margin;

    pdf.addImage(imgData, 'JPEG', margin, position, imgWidth, imgHeight);
    heightLeft -= printableHeight;

    while (heightLeft > 0) {
      position = margin - (imgHeight - heightLeft);
      pdf.addPage();
      pdf.addImage(imgData, 'JPEG', margin, position, imgWidth, imgHeight);
      heightLeft -= printableHeight;
    }

    pdf.save(filename);
    console.log('[PDF Export Debug] Live PDF successfully saved:', filename);
    return true;
  } catch (err) {
    console.warn('[PDF Export Debug] Live DOM capture exception:', err);
    return false; // Triggers fallback to template generator
  } finally {
    window.scrollTo(0, originalScrollY);
  }
};

/* ═══════════════════════════════════════════════════════════════
   REPORT 1: Full Skill Gap Analysis Page PDF
════════════════════════════════════════════════════════════════ */
export const generateFullReportPDF = async (data) => {
  if (!validateData(data)) return false;

  const info = data.candidate_info || {};
  const role = data.target_role || 'Software Engineer';
  const matchScore = data.resume_match_score ?? data.skill_match_percentage ?? 0;
  const readiness = data.ai_readiness_score ?? data.career_readiness?.percentage ?? 0;
  const hiringProb = data.hiring_probability ?? 0;
  const strong = data.strong_skills || [];
  const partial = data.partial_skills || [];
  const priority = data.priority_skills || [];
  const benchmark = data.industry_benchmark || [];
  const roadmap = data.learning_roadmap || [];
  const certs = data.recommended_certifications || [];
  const projects = data.recommended_projects || [];
  const ats = data.ats_improvement_report || {};
  const interview = data.interview_readiness || {};
  const recommendations = data.ai_recommendations || {};

  const html = `
    ${getReportHeader('Complete Skill Gap Analysis & Roadmap', info, role)}

    <!-- Score Overview Banner -->
    <div style="display: flex; gap: 12px; margin-bottom: 20px;">
      <div style="flex: 1; background: #eef2ff; border: 1px solid #c7d2fe; border-radius: 8px; padding: 14px; text-align: center;">
        <span style="font-size: 26px; font-weight: 800; color: #4338ca;">${matchScore}%</span>
        <p style="font-size: 10px; font-weight: 700; color: #3730a3; margin: 4px 0 0 0; text-transform: uppercase;">Resume Match Score</p>
      </div>
      <div style="flex: 1; background: #ecfdf5; border: 1px solid #a7f3d0; border-radius: 8px; padding: 14px; text-align: center;">
        <span style="font-size: 26px; font-weight: 800; color: #047857;">${readiness}%</span>
        <p style="font-size: 10px; font-weight: 700; color: #065f46; margin: 4px 0 0 0; text-transform: uppercase;">AI Readiness Score</p>
      </div>
      <div style="flex: 1; background: #fffbeb; border: 1px solid #fde68a; border-radius: 8px; padding: 14px; text-align: center;">
        <span style="font-size: 26px; font-weight: 800; color: #b45309;">${hiringProb}%</span>
        <p style="font-size: 10px; font-weight: 700; color: #92400e; margin: 4px 0 0 0; text-transform: uppercase;">Hiring Probability</p>
      </div>
    </div>

    <!-- AI Executive Summary -->
    ${data.skill_gap_summary ? `
      <div style="background: #f8fafc; border-left: 4px solid #4f46e5; padding: 12px 14px; margin-bottom: 20px; border-radius: 4px;">
        <h3 style="font-size: 11px; font-weight: 700; color: #4f46e5; margin: 0 0 4px 0; text-transform: uppercase;">AI Executive Summary</h3>
        <p style="font-size: 11px; color: #334155; margin: 0; line-height: 1.5;">${data.skill_gap_summary}</p>
      </div>
    ` : ''}

    <!-- Competency Breakdown -->
    <h3 style="font-size: 13px; font-weight: 700; color: #0f172a; margin: 16px 0 8px 0; border-bottom: 1px solid #cbd5e1; padding-bottom: 4px;">1. Competency Breakdown</h3>
    <div style="display: flex; gap: 12px; margin-bottom: 20px;">
      <div style="flex: 1; background: #fafafa; border: 1px solid #e2e8f0; border-radius: 6px; padding: 10px;">
        <h4 style="font-size: 11px; font-weight: 700; color: #166534; margin: 0 0 6px 0;">Strong Skills (${strong.length})</h4>
        ${strong.slice(0, 8).map(s => `<div style="font-size: 10px; color: #15803d; margin-bottom: 3px;">✓ ${s.skill || s.name} (${s.confidence_pct || 80}%)</div>`).join('')}
      </div>
      <div style="flex: 1; background: #fafafa; border: 1px solid #e2e8f0; border-radius: 6px; padding: 10px;">
        <h4 style="font-size: 11px; font-weight: 700; color: #854d0e; margin: 0 0 6px 0;">Partial Skills (${partial.length})</h4>
        ${partial.slice(0, 8).map(s => `<div style="font-size: 10px; color: #a16207; margin-bottom: 3px;">~ ${s.skill || s.name} (${s.confidence_pct || 50}%)</div>`).join('')}
      </div>
      <div style="flex: 1; background: #fafafa; border: 1px solid #e2e8f0; border-radius: 6px; padding: 10px;">
        <h4 style="font-size: 11px; font-weight: 700; color: #991b1b; margin: 0 0 6px 0;">Missing Skills (${priority.length})</h4>
        ${priority.slice(0, 8).map(s => `<div style="font-size: 10px; color: #dc2626; margin-bottom: 3px;">✗ ${s.skill || s.name} [${s.priority || 'High'}]</div>`).join('')}
      </div>
    </div>

    <!-- Industry Benchmark Table -->
    ${benchmark.length > 0 ? `
      <h3 style="font-size: 13px; font-weight: 700; color: #0f172a; margin: 16px 0 8px 0; border-bottom: 1px solid #cbd5e1; padding-bottom: 4px;">2. Industry Benchmark Comparison</h3>
      <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px; font-size: 10px;">
        <thead>
          <tr style="background: #f1f5f9; text-align: left;">
            <th style="padding: 6px; border: 1px solid #cbd5e1;">Skill / Technology Category</th>
            <th style="padding: 6px; border: 1px solid #cbd5e1; text-align: center;">Resume Status</th>
            <th style="padding: 6px; border: 1px solid #cbd5e1; text-align: center;">Industry Requirement</th>
          </tr>
        </thead>
        <tbody>
          ${benchmark.slice(0, 10).map(b => `
            <tr>
              <td style="padding: 5px 6px; border: 1px solid #e2e8f0; font-weight: 600;">${b.category}</td>
              <td style="padding: 5px 6px; border: 1px solid #e2e8f0; text-align: center; color: ${b.resume_has ? '#166534' : '#991b1b'}; font-weight: 700;">
                ${b.resume_has ? '✓ Covered' : '✗ Gap'}
              </td>
              <td style="padding: 5px 6px; border: 1px solid #e2e8f0; text-align: center; color: #1e293b;">Required</td>
            </tr>
          `).join('')}
        </tbody>
      </table>
    ` : ''}

    <!-- 5-Phase Roadmap -->
    ${roadmap.length > 0 ? `
      <h3 style="font-size: 13px; font-weight: 700; color: #0f172a; margin: 16px 0 8px 0; border-bottom: 1px solid #cbd5e1; padding-bottom: 4px;">3. 5-Phase Learning Roadmap</h3>
      <div style="margin-bottom: 20px;">
        ${roadmap.slice(0, 5).map((p, idx) => `
          <div style="background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 6px; padding: 8px 12px; margin-bottom: 6px;">
            <div style="display: flex; justify-content: space-between; font-size: 11px; font-weight: 700; color: #1e1b4b;">
              <span>${p.phase || `Phase ${idx+1}`}: ${p.phase_name || p.title || ''}</span>
              <span style="color: #4f46e5;">Duration: ${p.duration || '3 Weeks'} | Progress: ${p.completion_pct || 0}%</span>
            </div>
            <p style="font-size: 10px; color: #475569; margin: 3px 0 0 0;">
              <strong>Skills:</strong> ${Array.isArray(p.skills) ? p.skills.join(', ') : p.skills}
            </p>
          </div>
        `).join('')}
      </div>
    ` : ''}

    <!-- Certifications & Projects -->
    <div style="display: flex; gap: 12px; margin-bottom: 20px;">
      ${certs.length > 0 ? `
        <div style="flex: 1; background: #fafafa; border: 1px solid #e2e8f0; border-radius: 6px; padding: 10px;">
          <h4 style="font-size: 11px; font-weight: 700; color: #6b21a8; margin: 0 0 6px 0;">Recommended Certifications</h4>
          ${certs.slice(0, 3).map(c => `
            <div style="font-size: 10px; margin-bottom: 4px;">
              <strong>${c.name}</strong> (${c.provider}) - <em>${c.duration}</em>
            </div>
          `).join('')}
        </div>
      ` : ''}

      ${projects.length > 0 ? `
        <div style="flex: 1; background: #fafafa; border: 1px solid #e2e8f0; border-radius: 6px; padding: 10px;">
          <h4 style="font-size: 11px; font-weight: 700; color: #1e40af; margin: 0 0 6px 0;">Capstone Projects</h4>
          ${projects.slice(0, 2).map(pr => `
            <div style="font-size: 10px; margin-bottom: 4px;">
              <strong>${pr.project_name}</strong> - <em>Impact: ${pr.resume_impact || 'High'}</em>
            </div>
          `).join('')}
        </div>
      ` : ''}
    </div>

    <!-- ATS & Interview Readiness -->
    <div style="display: flex; gap: 12px; margin-bottom: 20px;">
      <div style="flex: 1; background: #fafafa; border: 1px solid #e2e8f0; border-radius: 6px; padding: 10px;">
        <h4 style="font-size: 11px; font-weight: 700; color: #047857; margin: 0 0 6px 0;">ATS Optimization Report</h4>
        <p style="font-size: 10px; margin: 0 0 4px 0;">Current Score: <strong>${ats.current_ats_score || matchScore}%</strong> | Target: <strong style="color:#047857;">${ats.expected_ats_score || 92}%</strong></p>
        <p style="font-size: 9px; color: #475569; margin: 0;"><strong>Missing Keywords:</strong> ${(ats.missing_keywords || []).slice(0, 6).join(', ')}</p>
      </div>

      <div style="flex: 1; background: #fafafa; border: 1px solid #e2e8f0; border-radius: 6px; padding: 10px;">
        <h4 style="font-size: 11px; font-weight: 700; color: #b45309; margin: 0 0 6px 0;">Interview Readiness Scorecard</h4>
        <p style="font-size: 10px; margin: 0 0 2px 0;">Technical: <strong>${interview.technical_skills || 60}%</strong> | Projects: <strong>${interview.projects || 60}%</strong></p>
        <p style="font-size: 10px; margin: 0 0 2px 0;">Communication: <strong>${interview.communication || 75}%</strong> | Overall: <strong style="color:#047857;">${interview.overall_interview_readiness || 65}%</strong></p>
      </div>
    </div>

    <!-- AI Guidance -->
    ${recommendations.best_next_learning_path ? `
      <div style="background: #f1f5f9; border: 1px solid #cbd5e1; border-radius: 6px; padding: 10px; margin-bottom: 10px;">
        <h4 style="font-size: 11px; font-weight: 700; color: #4f46e5; margin: 0 0 4px 0;">AI Career Next Path</h4>
        <p style="font-size: 10px; color: #334155; margin: 0;">${recommendations.best_next_learning_path}</p>
      </div>
    ` : ''}

    ${getReportFooter()}
  `;

  return renderPDF(html, 'CareerOS_AI_Skill_Gap_Full_Report.pdf');
};

/* ═══════════════════════════════════════════════════════════════
   REPORT 2: Skill Gap Analysis Report PDF
════════════════════════════════════════════════════════════════ */
export const generateSkillGapPDF = async (data) => {
  if (!validateData(data)) return false;

  const info = data.candidate_info || {};
  const role = data.target_role || 'Software Engineer';
  const matchScore = data.resume_match_score ?? data.skill_match_percentage ?? 0;
  const strong = data.strong_skills || [];
  const priority = data.priority_skills || [];

  const html = `
    ${getReportHeader('Skill Gap Analysis Report', info, role)}

    <div style="background: #eef2ff; border: 1px solid #c7d2fe; border-radius: 8px; padding: 14px; text-align: center; margin-bottom: 20px;">
      <span style="font-size: 28px; font-weight: 800; color: #4338ca;">${matchScore}%</span>
      <p style="font-size: 11px; font-weight: 700; color: #3730a3; margin: 4px 0 0 0; text-transform: uppercase;">Overall Skill Match Score against ${role}</p>
    </div>

    ${data.skill_gap_summary ? `
      <div style="background: #f8fafc; border-left: 4px solid #4f46e5; padding: 10px 14px; margin-bottom: 20px;">
        <h3 style="font-size: 11px; font-weight: 700; color: #4f46e5; margin: 0 0 4px 0; text-transform: uppercase;">AI Professional Assessment</h3>
        <p style="font-size: 11px; color: #334155; margin: 0; line-height: 1.5;">${data.skill_gap_summary}</p>
      </div>
    ` : ''}

    <h3 style="font-size: 13px; font-weight: 700; color: #166534; margin: 16px 0 8px 0; border-bottom: 1px solid #bbf7d0; padding-bottom: 4px;">
      Verified Strong Competencies (${strong.length})
    </h3>
    <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px; font-size: 10px;">
      <thead>
        <tr style="background: #f0fdf4;">
          <th style="padding: 6px; border: 1px solid #cbd5e1; text-align: left;">Skill Name</th>
          <th style="padding: 6px; border: 1px solid #cbd5e1; text-align: center;">Confidence %</th>
          <th style="padding: 6px; border: 1px solid #cbd5e1; text-align: center;">Industry Relevance</th>
        </tr>
      </thead>
      <tbody>
        ${strong.map(s => `
          <tr>
            <td style="padding: 5px 6px; border: 1px solid #e2e8f0; font-weight: 600;">${s.skill || s.name}</td>
            <td style="padding: 5px 6px; border: 1px solid #e2e8f0; text-align: center;">${s.confidence_pct || 80}%</td>
            <td style="padding: 5px 6px; border: 1px solid #e2e8f0; text-align: center; color: #166534; font-weight: 700;">${s.industry_relevance || 'High'}</td>
          </tr>
        `).join('')}
      </tbody>
    </table>

    <h3 style="font-size: 13px; font-weight: 700; color: #991b1b; margin: 16px 0 8px 0; border-bottom: 1px solid #fecdd3; padding-bottom: 4px;">
      Critical Missing Competencies (${priority.length})
    </h3>
    <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px; font-size: 10px;">
      <thead>
        <tr style="background: #fef2f2;">
          <th style="padding: 6px; border: 1px solid #cbd5e1; text-align: left;">Missing Skill</th>
          <th style="padding: 6px; border: 1px solid #cbd5e1; text-align: center;">Priority</th>
          <th style="padding: 6px; border: 1px solid #cbd5e1; text-align: center;">Importance</th>
          <th style="padding: 6px; border: 1px solid #cbd5e1; text-align: center;">Difficulty</th>
          <th style="padding: 6px; border: 1px solid #cbd5e1; text-align: center;">Est. Time</th>
        </tr>
      </thead>
      <tbody>
        ${priority.map(s => `
          <tr>
            <td style="padding: 5px 6px; border: 1px solid #e2e8f0; font-weight: 600; color: #991b1b;">${s.skill || s.name}</td>
            <td style="padding: 5px 6px; border: 1px solid #e2e8f0; text-align: center; font-weight: 700; color: #dc2626;">${s.priority || 'High'}</td>
            <td style="padding: 5px 6px; border: 1px solid #e2e8f0; text-align: center;">${s.importance || 'Critical'}</td>
            <td style="padding: 5px 6px; border: 1px solid #e2e8f0; text-align: center;">${s.learning_difficulty || 'Moderate'}</td>
            <td style="padding: 5px 6px; border: 1px solid #e2e8f0; text-align: center;">${s.estimated_time || '2 Weeks'}</td>
          </tr>
        `).join('')}
      </tbody>
    </table>

    ${getReportFooter()}
  `;

  return renderPDF(html, 'Skill_Gap_Analysis_Report.pdf');
};

/* ═══════════════════════════════════════════════════════════════
   REPORT 3: Learning Roadmap Report PDF
════════════════════════════════════════════════════════════════ */
export const generateRoadmapPDF = async (data) => {
  if (!validateData(data)) return false;

  const info = data.candidate_info || {};
  const role = data.target_role || 'Software Engineer';
  const roadmap = data.learning_roadmap || [];

  const html = `
    ${getReportHeader('5-Phase Learning Roadmap', info, role)}

    <div style="background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 12px; margin-bottom: 20px; text-align: center;">
      <h2 style="font-size: 14px; font-weight: 800; color: #1e1b4b; margin: 0;">Personalized Action Plan for ${role}</h2>
      <p style="font-size: 11px; color: #64748b; margin: 4px 0 0 0;">Phase-by-phase competency development guide</p>
    </div>

    <div>
      ${roadmap.map((p, idx) => `
        <div style="background: #ffffff; border: 1px solid #cbd5e1; border-left: 4px solid #4f46e5; border-radius: 6px; padding: 12px; margin-bottom: 10px;">
          <div style="display: flex; justify-content: space-between; align-items: center; border-bottom: 1px solid #f1f5f9; padding-bottom: 6px; margin-bottom: 8px;">
            <span style="font-size: 12px; font-weight: 800; color: #1e1b4b;">${p.phase || `Phase ${idx+1}`}: ${p.phase_name || p.title || ''}</span>
            <span style="font-size: 10px; font-weight: 700; color: #4f46e5;">Duration: ${p.duration || '3 Weeks'} | Progress: ${p.completion_pct || 0}%</span>
          </div>

          <p style="font-size: 11px; color: #0f172a; margin: 0 0 6px 0;">
            <strong>Skills to Master:</strong> ${Array.isArray(p.skills) ? p.skills.join(', ') : p.skills}
          </p>

          ${p.tasks ? `
            <div style="font-size: 10px; color: #475569;">
              <strong>Actionable Tasks:</strong>
              <ul style="margin: 4px 0 0 0; padding-left: 16px;">
                ${(Array.isArray(p.tasks) ? p.tasks : [p.tasks]).map(t => `<li style="margin-bottom: 2px;">${t}</li>`).join('')}
              </ul>
            </div>
          ` : ''}
        </div>
      `).join('')}
    </div>

    ${getReportFooter()}
  `;

  return renderPDF(html, 'Learning_Roadmap.pdf');
};

/* ═══════════════════════════════════════════════════════════════
   REPORT 4: ATS Improvement Report PDF
════════════════════════════════════════════════════════════════ */
export const generateAtsPDF = async (data) => {
  if (!validateData(data)) return false;

  const info = data.candidate_info || {};
  const role = data.target_role || 'Software Engineer';
  const ats = data.ats_improvement_report || {};
  const matchScore = data.resume_match_score ?? data.skill_match_percentage ?? 0;

  const html = `
    ${getReportHeader('ATS Resume Improvement Report', info, role)}

    <div style="display: flex; gap: 14px; margin-bottom: 20px;">
      <div style="flex: 1; background: #f8fafc; border: 1px solid #cbd5e1; border-radius: 8px; padding: 14px; text-align: center;">
        <span style="font-size: 28px; font-weight: 800; color: #334155;">${ats.current_ats_score || matchScore}%</span>
        <p style="font-size: 10px; font-weight: 700; color: #64748b; margin: 4px 0 0 0; text-transform: uppercase;">Current ATS Parser Score</p>
      </div>
      <div style="flex: 1; background: #ecfdf5; border: 1px solid #a7f3d0; border-radius: 8px; padding: 14px; text-align: center;">
        <span style="font-size: 28px; font-weight: 800; color: #047857;">${ats.expected_ats_score || 92}%</span>
        <p style="font-size: 10px; font-weight: 700; color: #065f46; margin: 4px 0 0 0; text-transform: uppercase;">Target Potential ATS Score</p>
      </div>
    </div>

    <h3 style="font-size: 13px; font-weight: 700; color: #991b1b; margin: 16px 0 8px 0; border-bottom: 1px solid #fecdd3; padding-bottom: 4px;">
      Critical Missing Keywords for ATS Compatibility
    </h3>
    <div style="background: #fef2f2; border: 1px solid #fecdd3; border-radius: 6px; padding: 10px; margin-bottom: 20px;">
      <p style="font-size: 11px; color: #991b1b; margin: 0 0 8px 0; font-weight: 600;">
        Recruiter ATS screeners search for exact keyword matches. Include the following keywords in your resume:
      </p>
      <p style="font-size: 11px; font-weight: 700; color: #dc2626; margin: 0; line-height: 1.6;">
        ${(ats.missing_keywords || data.missing_skills || []).join(' • ')}
      </p>
    </div>

    <h3 style="font-size: 13px; font-weight: 700; color: #047857; margin: 16px 0 8px 0; border-bottom: 1px solid #a7f3d0; padding-bottom: 4px;">
      Actionable Resume Enhancement Suggestions
    </h3>
    <div style="margin-bottom: 20px;">
      ${(ats.improvement_suggestions || []).map(sug => `
        <div style="background: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 6px; padding: 8px 12px; margin-bottom: 6px; font-size: 11px; color: #166534;">
          ✓ ${sug}
        </div>
      `).join('')}
    </div>

    ${ats.score_improvement_explanation ? `
      <div style="background: #f8fafc; border-left: 4px solid #047857; padding: 10px 14px; margin-bottom: 20px; font-size: 11px; color: #334155;">
        <strong>Optimization Rationale:</strong> ${ats.score_improvement_explanation}
      </div>
    ` : ''}

    ${getReportFooter()}
  `;

  return renderPDF(html, 'ATS_Improvement_Report.pdf');
};

/* ═══════════════════════════════════════════════════════════════
   REPORT 5: AI Career Guidance Report PDF
════════════════════════════════════════════════════════════════ */
export const generateCareerGuidancePDF = async (data) => {
  if (!validateData(data)) return false;

  const info = data.candidate_info || {};
  const role = data.target_role || 'Software Engineer';
  const recommendations = data.ai_recommendations || {};
  const certs = data.recommended_certifications || [];
  const projects = data.recommended_projects || [];

  const html = `
    ${getReportHeader('AI Career Guidance & Mentorship', info, role)}

    ${recommendations.best_next_learning_path ? `
      <div style="background: #eef2ff; border: 1px solid #c7d2fe; border-radius: 8px; padding: 12px; margin-bottom: 20px;">
        <h3 style="font-size: 12px; font-weight: 700; color: #4338ca; margin: 0 0 4px 0; text-transform: uppercase;">Best Recommended Learning Trajectory</h3>
        <p style="font-size: 11px; color: #1e1b4b; margin: 0; line-height: 1.5;">${recommendations.best_next_learning_path}</p>
      </div>
    ` : ''}

    <h3 style="font-size: 13px; font-weight: 700; color: #0f172a; margin: 16px 0 8px 0; border-bottom: 1px solid #cbd5e1; padding-bottom: 4px;">
      1. Recommended Industry Certifications
    </h3>
    <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px; font-size: 10px;">
      <thead>
        <tr style="background: #faf5ff;">
          <th style="padding: 6px; border: 1px solid #cbd5e1; text-align: left;">Certification Title</th>
          <th style="padding: 6px; border: 1px solid #cbd5e1; text-align: left;">Provider</th>
          <th style="padding: 6px; border: 1px solid #cbd5e1; text-align: center;">Duration</th>
          <th style="padding: 6px; border: 1px solid #cbd5e1; text-align: center;">Industry Value</th>
        </tr>
      </thead>
      <tbody>
        ${certs.map(c => `
          <tr>
            <td style="padding: 5px 6px; border: 1px solid #e2e8f0; font-weight: 600;">${c.name}</td>
            <td style="padding: 5px 6px; border: 1px solid #e2e8f0;">${c.provider}</td>
            <td style="padding: 5px 6px; border: 1px solid #e2e8f0; text-align: center;">${c.duration}</td>
            <td style="padding: 5px 6px; border: 1px solid #e2e8f0; text-align: center; color: #6b21a8; font-weight: 700;">${c.industry_value}</td>
          </tr>
        `).join('')}
      </tbody>
    </table>

    <h3 style="font-size: 13px; font-weight: 700; color: #0f172a; margin: 16px 0 8px 0; border-bottom: 1px solid #cbd5e1; padding-bottom: 4px;">
      2. Recommended Portfolio Projects
    </h3>
    <div style="margin-bottom: 20px;">
      ${projects.map(pr => `
        <div style="background: #f8fafc; border: 1px solid #cbd5e1; border-radius: 6px; padding: 10px; margin-bottom: 8px;">
          <h4 style="font-size: 11px; font-weight: 700; color: #1e40af; margin: 0 0 4px 0;">${pr.project_name} (Difficulty: ${pr.difficulty || 'Advanced'})</h4>
          <p style="font-size: 10px; color: #334155; margin: 0 0 4px 0;">${pr.description}</p>
          <p style="font-size: 9px; color: #64748b; margin: 0;"><strong>Tech Stack:</strong> ${Array.isArray(pr.technologies_used) ? pr.technologies_used.join(', ') : pr.technologies_used}</p>
        </div>
      `).join('')}
    </div>

    <h3 style="font-size: 13px; font-weight: 700; color: #0f172a; margin: 16px 0 8px 0; border-bottom: 1px solid #cbd5e1; padding-bottom: 4px;">
      3. Interview Preparation & Growth Tips
    </h3>
    <div style="font-size: 10px; color: #334155; margin-bottom: 20px;">
      ${(recommendations.interview_preparation_tips || []).map(t => `<p style="margin: 0 0 4px 0;">• <strong>Interview Tip:</strong> ${t}</p>`).join('')}
      ${(recommendations.career_growth_suggestions || []).map(t => `<p style="margin: 0 0 4px 0;">• <strong>Growth Strategy:</strong> ${t}</p>`).join('')}
    </div>

    ${getReportFooter()}
  `;

  return renderPDF(html, 'Career_Guidance_Report.pdf');
};
